name: Version Upgrade
on:
  push:
    branches:
      - "main"

jobs:
  version-upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup git
        run: |
          git config --global user.name 'Ayondip Jana'
          git config --global user.email 'ayondip.jana@scalereal.com'
      - name: Upgrade and push version
        uses: phips28/gh-action-bump-version@master
        id: version_bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording: "feat,feature"
          major-wording: "BREAKING,major"
          patch-wording: "patch,fix"
          rc-wording: "pre,rc"
          tag-prefix: "v"

      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies with Yarn
        run: yarn install

      - name: Create staging environment file
        run: |
          echo "${{ secrets.ENV_SANDBOX }}" > .env.sandbox

      - name: Create production environment file
        run: |
          echo "${{ secrets.ENV_PRODUCTION }}" > .env.production

      - name: Build and zip the project for chrome|sandbox
        run: yarn zip:sandbox:chrome
      
      - name: Build and zip the project for chrome|production
        run: yarn zip:production:chrome

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: "${{ steps.version_bump.outputs.newTag }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
