name: Version Upgrade
on:
  push:
    branches:
      - "main"

jobs:
  version-upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup git
        run: |
          git config --global user.name 'Ayondip Jana'
          git config --global user.email 'ayondip.jana@scalereal.com'
      - name: Upgrade and push version
        uses: phips28/gh-action-bump-version@master
        id: version_bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording: "feat,feature"
          major-wording: "BREAKING,major"
          patch-wording: "patch,fix"
          rc-wording: "pre,rc"
          tag-prefix: "v"

      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies with Yarn
        run: yarn install

      - name: Build and zip the project
        run: yarn zip
      - name: test output
        run: |
          echo ${{steps.version_bump.outputs}}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: "v${{ steps.version_bump.outputs.newTag }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish GitHub release
        run: |
          echo $GITHUB_REF
          gh release create $GITHUB_REF dist/* --title "Release $GITHUB_REF" --notes "Release notes for $GITHUB_REF"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
