name: Build and Publish Release

on:
  push:
    tags:
      - "v*"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies with Yarn
        run: yarn install

      - name: Build and zip the project
        run: |
          yarn version --minor
          yarn zip

      - name: Create release assets
        run: |
          mkdir release
          ls
          cp -r dist/* release/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      - name: Publish GitHub release
        run: |
          gh release create $GITHUB_REF release/* --title "Release $GITHUB_REF" --notes "Release notes for $GITHUB_REF"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
